### ISSUE TITLE
Reconsider the repo name

### ISSUE THREAD

**Issue by sandstrom** [mtsmfm/language_server-ruby#18]
Great project! 😄 

Would it make sense to rename this to `language-server-ruby` or even better `language-server` or `language_server`?

It feels more consistent to use one separator (`-`) instead of two, and afaik dash for repo-names is the most common one.

~*I guess this question goes for the sibling project too ([language_server-protocol-ruby](https://github.com/mtsmfm/language_server-protocol-ruby)).*~

**Comment by adaedra** [comment]
Just passing through, this name is consistent with gem naming conventions : http://guides.rubygems.org/name-your-gem/.

**Comment by sandstrom** [comment]
I'm happy to be corrected 😄 , but in this case I don't see why the gem is consistent. 

From the example the gem name `net-http-digest_auth` should correspond to `Net::HTTP::DigestAuth` but I cannot find a class named `LanguageServer::Ruby` in this repo.

Please let me know if I've misunderstood things.

***

Also, I'd argue that even if such a file existed it's sort of like naming a gem for a Github SDK `github_sdk` instead of simply `github`.

**Comment by mtsmfm** [comment]
@sandstrom 

Thank you for your opinion!
As @adaedra remarked, I use `_` as a word separator and `-` as a namespace separator.
I want to use `LanguageServer` as a top level module so I named this gem as `language_server`.

> I still think it would be neat with another repo name, ideally just language_server.

Perhaps I create another language server for another language so I want to include "ruby" in my repo name.
And `language_server` and `language_server-protocol` are Ruby gems.
Obviously, it's for Ruby so I don't want to include "ruby" for gem name.

I'll close this issue for now but feel free to add comments or re-open this issue!
Anyway, I'm glad to hear your opinion!
