### ISSUE TITLE
Rubocop dosen't start with error on ci

### ISSUE THREAD

**Issue by steiley** [mtsmfm/language_server-ruby#49]
```
+ bin/rubocop
Error: The `Lint/RescueWithoutErrorClass` cop has been replaced by `Style/RescueStandardError`.
(obsolete configuration found in .rubocop-https---github-com-onk-onkcop-raw-v0-51-0-0-config-rubocop-yml, please update it)
Exited with code 2
```

https://circleci.com/gh/mtsmfm/language_server-ruby/248?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

The above error occurs on ci with Ruby 2.2 or Ruby 2.3
This error doesn't occur on my local environment(both docker and local machine).

Is there anyone who knows something?

**Comment by mtsmfm** [comment]
@steiley Could you rebase your branch?

Sorry I fixed Gemfile 2 days ago 🙇 

https://github.com/mtsmfm/language_server-ruby/commit/6cb9a477653f064dd308850a07755013f78e511b#diff-8b7db4d5cc4b8f6dc8feb7030baa2478

**Comment by steiley** [comment]
@mtsmfm 
Thank you for your response!

I rebased my branch before I ran rubocop.
Still it occurred.

https://circleci.com/gh/mtsmfm/language_server-ruby/248?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

I found a suspicious part in the above page.

`Using rubocop 0.51.0 from https://github.com/bbatsov/rubocop (at master@3122cc7)`

It is displayed in "docker-compose run $SERVICE_NAME bin/ci" step.

'master@3122cc7' is current HEAD.
'master@88d9e3b' is what you specified.

I think there is something wrong with handling of gemfile on ci.

**Comment by steiley** [comment]
It didn't occur in the latest build.
It may be better to investigate if it continues to occur.
Can I close this issue?

**Comment by mtsmfm** [comment]
> I rebased my branch before I ran rubocop.
> Still it occurred.

No. According to the commit hash 1a65fc5, the branch wasn't rebased.

![image](https://user-images.githubusercontent.com/1796864/32665508-d7154ee8-c677-11e7-9632-2d3d8a76d23b.png)

https://github.com/mtsmfm/language_server-ruby/blob/1a65fc5463090cb25b07b25d0bead9d109744653/Gemfile

**Comment by mtsmfm** [comment]
Fixed via https://github.com/mtsmfm/language_server-ruby/commit/6cb9a477653f064dd308850a07755013f78e511b#diff-8b7db4d5cc4b8f6dc8feb7030baa2478

**Comment by steiley** [comment]
Thank you.
I appreciate your information.
I got it.
